config/routes.rb
SubsTest::Application.routes.draw do
  resources :subs
  root :to => "test_video#index"

end

app/models/sub.rb
class Sub < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  # GET /subs
  # GET /subs.xml
  def index
    @subs = Sub.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @subs }
    end
  end

  # GET /subs/1
  # GET /subs/1.xml
  def show
    @sub = Sub.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sub }
    end
  end

  # GET /subs/new
  # GET /subs/new.xml
  def new
    @sub = Sub.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sub }
    end
  end

  # GET /subs/1/edit
  def edit
    @sub = Sub.find(params[:id])
  end

  # POST /subs
  # POST /subs.xml
  def create
    @sub = Sub.new(params[:sub])

    respond_to do |format|
      if @sub.save
        format.html { redirect_to(@sub, :notice => 'Sub was successfully created.') }
        format.xml  { render :xml => @sub, :status => :created, :location => @sub }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sub.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /subs/1
  # PUT /subs/1.xml
  def update
    @sub = Sub.find(params[:id])

    respond_to do |format|
      if @sub.update_attributes(params[:sub])
        format.html { redirect_to(@sub, :notice => 'Sub was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sub.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /subs/1
  # DELETE /subs/1.xml
  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy

    respond_to do |format|
      format.html { redirect_to(subs_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/test_video_controller.rb
class TestVideoController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/test_video_helper.rb
module TestVideoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SubsTest</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "jquery"%>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/subs/_form.html.erb
<%= form_for(@sub) do |f| %>
  <% if @sub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub.errors.count, "error") %> prohibited this sub from being saved:</h2>

      <ul>
      <% @sub.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from %><br />
    <%= f.text_field :from %>
  </div>
  <div class="field">
    <%= f.label :to %><br />
    <%= f.text_field :to %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subs/edit.html.erb
<h1>Editing sub</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub %> |
<%= link_to 'Back', subs_path %>

app/views/subs/index.html.erb
<h1>Listing subs</h1>

<table>
  <tr>
    <th>From</th>
    <th>To</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subs.each do |sub| %>
  <tr>
    <td><%= sub.from %></td>
    <td><%= sub.to %></td>
    <td><%= sub.text %></td>
    <td><%= link_to 'Show', sub %></td>
    <td><%= link_to 'Edit', edit_sub_path(sub) %></td>
    <td><%= link_to 'Destroy', sub, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sub', new_sub_path %>

app/views/subs/new.html.erb
<h1>New sub</h1>

<%= render 'form' %>

<%= link_to 'Back', subs_path %>

app/views/subs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>From:</b>
  <%= @sub.from %>
</p>

<p>
  <b>To:</b>
  <%= @sub.to %>
</p>

<p>
  <b>Text:</b>
  <%= @sub.text %>
</p>


<%= link_to 'Edit', edit_sub_path(@sub) %> |
<%= link_to 'Back', subs_path %>

app/views/test_video/index.html.erb
<h2>测试视频字幕</h2>
<div>
  <video id="video" controls autoplay="autoplay">
    <source src='/test.mp4'>
  </video>
  <div id='subs_container'>
  </div>
</div>
<table>
  <%Sub.all.each do |sub|%>
    <tr>
      <td><a href="#" class="btn_from" data-time="<%=sub.from %>"><%=sub.from%></a></td>
      <td><a href="#" class="btn_to" data-time="<%=sub.to %>"><%=sub.to%></a></td>
      <td><span class='subs_text'><%=sub.subs_text %></span></td>
    </tr>
  <%end%>
</table>
<script type='text/javascript'>
  jQuery(function($){
      //var the_video = $('#video');
      var the_video = document.getElementsByTagName("video")[0]; 
      console.log(the_video);
      $('.btn_from').click(function(){
        var from_time=$(this).data('time');
        //alert(from_time);
        var start = parseFloat(from_time);
        the_video.currentTime=start;
        //the_video.pause();
        //the_video.currentTime=100000000;
        //alert(the_video.currentTime);
        the_video.play();
        });
      });
</script>